# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'EAKit' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EAKit

#网络
pod 'AFNetworking'

#工具
pod 'MJExtension'
pod 'CocoaLumberjack'
pod 'SDiPhoneVersion'
pod 'YYKit'

pod 'MBProgressHUD'
pod 'SVProgressHUD'

pod 'Masonry'

#WebView
pod 'WebViewJavascriptBridge'
pod 'NJKWebViewProgress'

#友盟
pod 'UMengAnalytics-NO-IDFA'

#动画
pod 'pop'

#主题
pod 'EATheme'

#dataBase
pod 'FMDB'

end
